// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache/cache_service.proto

package cache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CacheKeyRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheKeyRequest) Reset()         { *m = CacheKeyRequest{} }
func (m *CacheKeyRequest) String() string { return proto.CompactTextString(m) }
func (*CacheKeyRequest) ProtoMessage()    {}
func (*CacheKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7933906ce719ddba, []int{0}
}

func (m *CacheKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheKeyRequest.Unmarshal(m, b)
}
func (m *CacheKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheKeyRequest.Marshal(b, m, deterministic)
}
func (m *CacheKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheKeyRequest.Merge(m, src)
}
func (m *CacheKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CacheKeyRequest.Size(m)
}
func (m *CacheKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CacheKeyRequest proto.InternalMessageInfo

func (m *CacheKeyRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type CacheMessage struct {
	Key                  []byte               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CacheMessage) Reset()         { *m = CacheMessage{} }
func (m *CacheMessage) String() string { return proto.CompactTextString(m) }
func (*CacheMessage) ProtoMessage()    {}
func (*CacheMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7933906ce719ddba, []int{1}
}

func (m *CacheMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheMessage.Unmarshal(m, b)
}
func (m *CacheMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheMessage.Marshal(b, m, deterministic)
}
func (m *CacheMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheMessage.Merge(m, src)
}
func (m *CacheMessage) XXX_Size() int {
	return xxx_messageInfo_CacheMessage.Size(m)
}
func (m *CacheMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CacheMessage proto.InternalMessageInfo

func (m *CacheMessage) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CacheMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CacheMessage) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type CacheListRequest struct {
	Limit                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CacheListRequest) Reset()         { *m = CacheListRequest{} }
func (m *CacheListRequest) String() string { return proto.CompactTextString(m) }
func (*CacheListRequest) ProtoMessage()    {}
func (*CacheListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7933906ce719ddba, []int{2}
}

func (m *CacheListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheListRequest.Unmarshal(m, b)
}
func (m *CacheListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheListRequest.Marshal(b, m, deterministic)
}
func (m *CacheListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheListRequest.Merge(m, src)
}
func (m *CacheListRequest) XXX_Size() int {
	return xxx_messageInfo_CacheListRequest.Size(m)
}
func (m *CacheListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CacheListRequest proto.InternalMessageInfo

func (m *CacheListRequest) GetLimit() *wrappers.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *CacheListRequest) GetOffset() *wrappers.UInt32Value {
	if m != nil {
		return m.Offset
	}
	return nil
}

type CacheListResponse struct {
	Items                []*CacheMessage `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CacheListResponse) Reset()         { *m = CacheListResponse{} }
func (m *CacheListResponse) String() string { return proto.CompactTextString(m) }
func (*CacheListResponse) ProtoMessage()    {}
func (*CacheListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7933906ce719ddba, []int{3}
}

func (m *CacheListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheListResponse.Unmarshal(m, b)
}
func (m *CacheListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheListResponse.Marshal(b, m, deterministic)
}
func (m *CacheListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheListResponse.Merge(m, src)
}
func (m *CacheListResponse) XXX_Size() int {
	return xxx_messageInfo_CacheListResponse.Size(m)
}
func (m *CacheListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CacheListResponse proto.InternalMessageInfo

func (m *CacheListResponse) GetItems() []*CacheMessage {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*CacheKeyRequest)(nil), "cache.v1.CacheKeyRequest")
	proto.RegisterType((*CacheMessage)(nil), "cache.v1.CacheMessage")
	proto.RegisterType((*CacheListRequest)(nil), "cache.v1.CacheListRequest")
	proto.RegisterType((*CacheListResponse)(nil), "cache.v1.CacheListResponse")
}

func init() { proto.RegisterFile("cache/cache_service.proto", fileDescriptor_7933906ce719ddba) }

var fileDescriptor_7933906ce719ddba = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x55, 0x6a, 0x12, 0xc1, 0x75, 0xa5, 0x36, 0x23, 0x04, 0xae, 0xa9, 0x20, 0x32, 0x9b, 0x08,
	0xc1, 0x98, 0xba, 0xac, 0xd8, 0xf1, 0x90, 0x00, 0xf1, 0x10, 0x98, 0xc2, 0x82, 0x0d, 0x1a, 0x5b,
	0x37, 0xce, 0x50, 0xdb, 0x63, 0x3c, 0x63, 0x43, 0x04, 0x6c, 0xf8, 0x05, 0xf6, 0xfc, 0x14, 0xbf,
	0xc0, 0x87, 0x20, 0xcf, 0xd8, 0xd4, 0x8a, 0xa9, 0x22, 0xd4, 0x4d, 0x94, 0x39, 0xf7, 0xdc, 0x73,
	0xae, 0xef, 0x03, 0xf6, 0x62, 0x16, 0x2f, 0xd1, 0xd7, 0xbf, 0xef, 0x25, 0x96, 0x35, 0x8f, 0x91,
	0x16, 0xa5, 0x50, 0x82, 0x9c, 0xd7, 0x20, 0xad, 0x0f, 0xdc, 0x6b, 0x89, 0x10, 0x49, 0x8a, 0xbe,
	0xc6, 0xa3, 0x6a, 0xe1, 0x2b, 0x9e, 0xa1, 0x54, 0x2c, 0x2b, 0x0c, 0xd5, 0xbd, 0xba, 0x4e, 0xf8,
	0x54, 0xb2, 0xa2, 0xc0, 0x52, 0xb6, 0xf1, 0xfd, 0x36, 0xce, 0x0a, 0xee, 0xb3, 0x3c, 0x17, 0x8a,
	0x29, 0x2e, 0xf2, 0x36, 0xea, 0x5d, 0x87, 0x9d, 0x07, 0x8d, 0xd5, 0x53, 0x5c, 0x85, 0xf8, 0xb1,
	0x42, 0xa9, 0xc8, 0x2e, 0x58, 0xc7, 0xb8, 0x72, 0x46, 0xb3, 0xd1, 0x7c, 0x3b, 0x6c, 0xfe, 0x7a,
	0x25, 0x6c, 0x6b, 0xd2, 0x73, 0x94, 0x92, 0x25, 0x38, 0x64, 0x90, 0x8b, 0x30, 0xae, 0x59, 0x5a,
	0xa1, 0xb3, 0xa5, 0x31, 0xf3, 0x20, 0x77, 0x01, 0xf0, 0x73, 0xc1, 0x4b, 0xed, 0xe8, 0x58, 0xb3,
	0xd1, 0xdc, 0x0e, 0x5c, 0x6a, 0xea, 0xa1, 0x5d, 0xbd, 0xf4, 0xa8, 0xfb, 0xa0, 0xb0, 0xc7, 0xf6,
	0xbe, 0xc2, 0xae, 0xf6, 0x7c, 0xc6, 0xa5, 0xea, 0x2a, 0x0b, 0x60, 0x9c, 0xf2, 0x8c, 0x2b, 0xed,
	0x6c, 0x07, 0xfb, 0x03, 0xa9, 0x37, 0x4f, 0x72, 0x75, 0x18, 0xbc, 0x6d, 0xcc, 0x43, 0x43, 0x25,
	0x77, 0x60, 0x22, 0x16, 0x0b, 0x89, 0x4a, 0x97, 0xb6, 0x29, 0xa9, 0xe5, 0x7a, 0xf7, 0x60, 0xda,
	0x73, 0x97, 0x85, 0xc8, 0x25, 0x92, 0x9b, 0x30, 0xe6, 0x0a, 0x33, 0xe9, 0x8c, 0x66, 0xd6, 0xdc,
	0x0e, 0x2e, 0xd1, 0x6e, 0x48, 0xb4, 0xdf, 0x9d, 0xd0, 0x90, 0x82, 0x9f, 0x16, 0x8c, 0x35, 0x4e,
	0x1e, 0x83, 0xf5, 0xb2, 0x52, 0xe4, 0x14, 0xbe, 0x7b, 0x0a, 0xee, 0x4d, 0xbf, 0xff, 0xfa, 0xfd,
	0x63, 0xcb, 0xf6, 0x2e, 0xf8, 0xf5, 0x81, 0x59, 0x12, 0xf2, 0x02, 0xac, 0xd7, 0xf8, 0xff, 0x4a,
	0x97, 0xb5, 0xd2, 0xd4, 0xdd, 0xf9, 0xab, 0xe4, 0x7f, 0x39, 0xc6, 0xd5, 0x37, 0xf2, 0x0a, 0xac,
	0x47, 0xa8, 0xc8, 0xde, 0x5a, 0xde, 0xc9, 0x32, 0x6c, 0x92, 0x24, 0x03, 0xc9, 0x23, 0x98, 0x3c,
	0xc4, 0x14, 0x15, 0x9e, 0x41, 0xf5, 0xc6, 0x40, 0x35, 0x84, 0x73, 0xcd, 0x28, 0x88, 0xbb, 0x96,
	0xd8, 0xdb, 0x0e, 0xf7, 0xca, 0x3f, 0x63, 0x66, 0x76, 0x5d, 0x33, 0xc9, 0x49, 0x33, 0xef, 0x07,
	0xef, 0x6e, 0x27, 0x5c, 0x2d, 0xab, 0x88, 0xc6, 0x22, 0xf3, 0x3f, 0x88, 0x65, 0x1e, 0x61, 0x9a,
	0x8a, 0xbc, 0xbd, 0xc8, 0x5b, 0xed, 0x45, 0x9a, 0xc3, 0x32, 0x58, 0x34, 0xd1, 0x8f, 0xc3, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xff, 0x59, 0xcb, 0x59, 0xbb, 0x03, 0x00, 0x00,
}
